### ISSUE TITLE
Dodanie marginesu do kotwic wewnątrz artykułów

### ISSUE THREAD

**Issue by furious-programming** [pradoslaw/coyote#399]
Po otwarciu strony artykułu za pomocą linku zakończonego kotwicą, np.:

https://4programmers.net/Delphi/Artykuły/Implementacja_listy_dwukierunkowej_ze_znacznikiem#implementacja-w-jezyku-free-pascal

tytuł punktu z kotwicą jest schowany pod głównym menu serwisu:

![wrong](https://user-images.githubusercontent.com/8170730/32248621-7c700c24-be86-11e7-9d32-0054e5d747fb.png)

a powinien być widoczny:

![good](https://user-images.githubusercontent.com/8170730/32248653-a0c2f046-be86-11e7-8b8c-1184881978ce.png)

Przyda się ostylować miejsce docelowe – u siebie mam to rozwiązane w ten sposób:

```css
:target:before {
  content: '';
  display: block;
  height: 100px;
  margin: -100px 0 0;
}
```
i działa prawidłowo.
