### ISSUE TITLE
Avatar nachodzi na inny avatar na liście wiadomości

### ISSUE THREAD

**Issue by Danon** [pradoslaw/coyote#720]
![image](https://user-images.githubusercontent.com/13367735/217553733-2f916695-eaca-48c3-983a-334e13389b4a.png)

**Comment by goldipl** [comment]
Poprawka w CSS
```css
.mw-100 {
    max-width: 100%!important;
    width: 35px;
    height: 35px;
    object-fit: contain;
}
```

**Comment by Danon** [comment]
@goldipl Jak ustawiasz `width` i `height`, to `max-width` jest niepotrzebne. I swoją drogą żeby util `mw-100` ustawiał stałą szerokośc też jest średnie, więc ja proponuje:

```css
.avatar-size {
    object-fit: contain;
    width: 35px;
    height: 35px;
}
```
